name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          g++ \
          cmake \
          libgtest-dev \
          libgmock-dev \
          pkg-config
        
        # Verificar instalación de Google Test
        dpkg -l | grep gtest
    
    - name: Build tests
      run: |
        cd test
        make all
    
    - name: Run all tests
      run: |
        cd test
        make test_all
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test/build/
        retention-days: 7
    
    - name: Cleanup
      if: always()
      run: |
        cd test
        rm -rf build/*
